#  Copyright 2018 U.C. Berkeley RISE Lab
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: sharedmemory-pod-NUM_DUMMY
  labels: 
    role: sharedmemory
spec:
  hostNetwork: true
  containers:
  - name: sharedmemory-container
    image: vsreekanti/anna
    env: 
    - name: SERVER_TYPE
      value: "3"
    - name: ROUTING_IPS
      value: ROUTING_IPS_DUMMY
    - name: MGMT_IP
      value: MGMT_IP_DUMMY
    - name: SEED_IP
      value: SEED_IP_DUMMY
    - name: MON_IPS
      value: MON_IPS_DUMMY
  nodeSelector:
    role: sharedmemory
    podid: sharedmemory-NUM_DUMMY
